apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-k8s
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        imagePullPolicy: IfNotPresent
        image: jeffqev/backend-k8s:latest
---
apiVersion: v1
kind: Service
metadata:
  name: backend-k8s
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
