apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-k8s
  labels:
    app: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: IfNotPresent
        image: frontend-k8s:v1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-k8s
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
